### ISSUE TITLE
Upgrade for multi-site

### ISSUE THREAD

**Issue by tylerhcarter** [x-team/wp-stream-data-generator#2]
Right now all of the entries created are not compatible with the multi-site additions to `wp-stream`.

**Comment by tylerhcarter** [comment]
Hold up... I'm doing something wrong on my end.

**Comment by tylerhcarter** [comment]
Nope, I can verify it does work. However, we might have a problem with x-team/wp-stream#65 while using a non-MS install.

**Comment by lukecarbis** [comment]
Thanks @chacha .
